version: '3.8'
services:
  db:
    build: ./db
    ports:
      - 5432:5432
  backend:
    build: ./backend
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/backend
volumes:
  postgres_data: