version: '3.8'
services:
  db:
    build: ./db
    ports:
      - 5432:5432
  backend:
    build: ./backend
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/backend
  bot:
    build: ./bot
    volumes:
      - ./bot:/bot
    depends_on:
      - backend
    restart: always
volumes:
  postgres_data: