version: '3.8'
services:
  db:
    build: ./db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/backend
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 3000:80
  #   volumes:
  #     - ./frontend:/app
  bot:
    build: ./bot
    volumes:
      - ./bot:/bot
    depends_on:
      - backend
    restart: always
volumes:
  postgres_data: