version: '3.8'
services:
  db:
    build: ./db
    ports:
      - 5432:5432
    environment:
      - TZ=Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TZ=Europe/Moscow
    volumes:
      - ./backend:/backend
  bot:
    build: ./bot
    volumes:
      - ./bot:/bot
    depends_on:
      - backend
    restart: always
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  postgres_data: